import NavBar from "@/components/layout/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  locales,
}: Readonly<{
  children: React.ReactNode;
  locales: React.ReactNode;
}>) {
  return (
    <>
      <NavBar>{locales}</NavBar>
      {children}
    </>
  );
}
