import { ResponsiveBlogNewsGrid } from "@/components/blog/responsive-blog-news-grid";
import { Blog as BlogType } from "@/types";

export default function BlogPage() {
  const blogs: BlogType[] = [
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
  ];
  return (
    <div>
      <ResponsiveBlogNewsGrid blogs={blogs} />
    </div>
  );
}
