import { ResponsiveBlogNewsGrid } from "@/components/blog/responsive-blog-news-grid";
import { Blog as BlogType } from "@/types";

export default function BlogPage() {
  const blogs: BlogType[] = [
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "How to get the best luxury property in Algarve",
      author: "Marcela Boturao",
      readTime: 6,
      date: "03.24.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "The best restaurants in Algarve for a perfect dinner",
      author: "Rodrigo Boturao",
      readTime: 8,
      date: "03.25.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "The best beaches in Algarve for a relaxing day",
      author: "Leticia Boturao",
      readTime: 5,
      date: "03.26.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "The best golf courses in Algarve for a perfect round",
      author: "Marcelo Boturao",
      readTime: 7,
      date: "03.27.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "Luxury villa rentals in Algarve: A complete guide",
      author: "Sofia Costa",
      readTime: 9,
      date: "03.28.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "Hidden culinary gems in Algarve's coastal towns",
      author: "Miguel Santos",
      readTime: 10,
      date: "03.29.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "Secret beaches of Algarve only locals know about",
      author: "Ana Silva",
      readTime: 4,
      date: "03.30.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "Championship golf courses in Algarve: Pro tips",
      author: "Carlos Pereira",
      readTime: 12,
      date: "03.31.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "Investment opportunities in Algarve real estate market",
      author: "Isabella Fernandes",
      readTime: 11,
      date: "04.01.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "Traditional Portuguese cuisine in Algarve",
      author: "José Oliveira",
      readTime: 6,
      date: "04.02.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "Family-friendly beaches in Algarve with activities",
      author: "Maria Rodrigues",
      readTime: 7,
      date: "04.03.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "Golf resorts in Algarve: Where luxury meets sport",
      author: "Pedro Martins",
      readTime: 8,
      date: "04.04.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "Algarve property market trends for 2025",
      author: "Catarina Alves",
      readTime: 13,
      date: "04.05.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "Michelin-starred restaurants in Algarve region",
      author: "António Ribeiro",
      readTime: 9,
      date: "04.06.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "Wild and untouched beaches of Western Algarve",
      author: "Teresa Lopes",
      readTime: 5,
      date: "04.07.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "Golf academies in Algarve for beginners",
      author: "Ricardo Sousa",
      readTime: 10,
      date: "04.08.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "Buying vs renting luxury properties in Algarve",
      author: "Joana Carvalho",
      readTime: 14,
      date: "04.09.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "Wine and dine experiences in Algarve vineyards",
      author: "Manuel Dias",
      readTime: 11,
      date: "04.10.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "Best surfing beaches in Algarve for all levels",
      author: "Beatriz Nunes",
      readTime: 8,
      date: "04.11.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "Historic golf clubs in Algarve: A legacy of excellence",
      author: "Fernando Moreira",
      readTime: 15,
      date: "04.12.2025",
    },
    {
      slug: "ciwkjwncwnkncw909",
      image: "/images/blog-img.png",
      title: "Sustainable luxury living in Algarve properties",
      author: "Luisa Gomes",
      readTime: 12,
      date: "04.13.2025",
    },
    {
      slug: "ciwkjwncwnkncw1010",
      image: "/images/blog-img.png",
      title: "Seafood festivals and culinary events in Algarve",
      author: "Vasco Teixeira",
      readTime: 7,
      date: "04.14.2025",
    },
    {
      slug: "ciwkjwncwnkncw1011",
      image: "/images/blog-img.png",
      title: "Romantic sunset beaches in Algarve for couples",
      author: "Cláudia Ferreira",
      readTime: 6,
      date: "04.15.2025",
    },
    {
      slug: "ciwkjwncwnkncw1012",
      image: "/images/blog-img.png",
      title: "Golf tourism in Algarve: Planning your perfect trip",
      author: "Nuno Barbosa",
      readTime: 16,
      date: "04.16.2025",
    },
  ];
  return (
    <div>
      <ResponsiveBlogNewsGrid blogs={blogs} />
    </div>
  );
}
